apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "2.31.5"
    chart: argo-rollouts
    helm:
      parameters:
        - name: dashboard.enabled
          value: 'true'      
      values: |
        server:
          global:
            scrape_interval: 10s
          ingress:
            enabled: true
            ingressClassName: kong
            hosts:
            #- argo-rollouts.local:3100
            - argo-rollouts.local
        dashboard:
          enabled: true
    path: argo-rollouts/base            
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true