apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "0.33.1"
    chart: argo-workflows
    helm:
      values: |
        server:
          global:
            scrape_interval: 10s
          ingress:
            enabled: true
            ingressClassName: kong
            hosts:
            - argo-workflows.local
    #path: argo-workflows/overlays/production            
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true