apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-mq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jeansampaio/kind-kong.git
    targetRevision: HEAD
    path: apps/rabbit-mq
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbits
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
