apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: mysql
  # deployed yaml
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jeansampaio/kind-kong.git
    path: repository/helm-charts/mysql
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        allowEmpty: true
        selfHeal: true